[browser]
gatherUsageStats = false

[server]
headless = true
port = 8502

[theme]
base = "dark"
primaryColor = "#9b59b6"
backgroundColor = "#0a141e"
secondaryBackgroundColor = "rgba(15, 32, 39, 0.6)"
textColor = "#ffffff"
